Parameters:
    InstanceTypeParameter:
        Type: String
        Default: t2.micro
        AllowedValues:
        - t2.micro
        - m1.small
        - m1.large
        Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
    Env:
        Type: String
        Default: Dev
        AllowedValues:
            - Staging
            - Dev
    # KeyName:
    #     Type: AWS::EC2::KeyPair::KeyName
    ImageIdParameter:
        Type: String
        Default: ami-0c2ab3b8efb09f272


Resources:
    InstanceSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Inbound Rules
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 22
                  ToPort: 22
                  CidrIp: 0.0.0.0/0

    InstanceforCustodian:
        Description: EC2 Instance for Custodian App
        Type: AWS::EC2::Instance
        Properties:
            ImageId:
                Ref: ImageIdParameter
            InstanceType:
                Ref: InstanceTypeParameter
            # KeyName: 
            #     Ref: KeyName
            SecurityGroups: 
                - Ref: InstanceSecurityGroup
            UserData:
                Fn::Base64: |
                    #!/bin/bash
                    yum update -y
                    yum install -y httpd.x86_64
                    systemctl start httpd.service
                    systemctl enable httpd.service
                    echo ?Hello World from $(hostname -f)? > /var/html/index.html
                # Fn::Base64: |
                #     #!/bin/bash
                #     yum update -y
                #     curl -sL https://rpm.nodesource.com/setup_lts.x | bash -
                #     yum install nodejs -y
