Parameters:
    InstanceTypeParameter:
        Type: String
        Default: t2.micro
        AllowedValues:
        - t2.micro
        - m1.small
        - m1.large
        Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
    Env:
        Type: String
        Default: Dev
        AllowedValues:
            - Staging
            - Dev
    KeyName:
        Type: AWS::EC2::KeyPair::KeyName
    ImageIdParameter:
        Type: String
        Default: ami-0d70546e43a941d70


Resources:
    InstanceSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Inbound Rules
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 22
                  ToPort: 22
                  CidrIp: 0.0.0.0/0

    InstanceforCustodian:
        Description: EC2 Instance for Custodian App
        Type: AWS::EC2::Instance
        Properties:
            ImageId:
                Ref: ImageIdParameter
            InstanceType:
                Ref: InstanceTypeParameter
            KeyName: 
                Ref: KeyName
            SecurityGroups: 
                - Ref: InstanceSecurityGroup
            UserData:
                Fn::Base64: |
                    #!/bin/bash
                    sudo apt-get update
                    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
                    export NVM_DIR="$HOME/.nvm"
                    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
                    nvm install 16.13.2
                    sudo apt-get install git
                    sudo apt install ruby-full